ospi:
  password: "YOUR_OSPI_PASSWORD" # Needs to be hashed. View README for help
  port: "8080"
stations: # Station activity notifications for start and stop. Valid options are "yes" or "no"
  notify:
    start: "yes"
    stop: "yes"
  messages: # Use {} as the place where the zone number will be displayed
    start: "Zone {} is now active"
    stop: "Zone {} is now idle" 
rain: # Rain sensor notifications for active or cleared. Valid options are "yes" or "no"
  notify: "yes"
  messages:
    active: "Rain sensor has detected rain"
    clear: "Rain sensor has cleared"
waterlevel: # Water level notifications? Valid options are "yes" or "no"
  notify: "yes"
  message: "The water level is now {}%"
push:
  service: "instapush" # Acceptable options are "instapush" or "pushover"
  instapush:
    appID: "YOUR_INSTAPUSH_APPID"
    appSecret: "YOUR_INSTAPUSH_APPSECRET"
  pushover:
    userKey: "YOUR_PUSHOVER_USERKEY"
    appToken: "YOUR_PUSHOVER_APPTOKEN"
  ifttt:
    eventName: "YOUR_IFTTT_EVENT_NAME"
    userKey: "YOUR_IFTTT_USER_KEY"
email:
  from: "you@yourdomain.com"
  to: "you@yourdomain.com"
  server: "localhost"
  subject: "OSPi Push Notification Script Failure"
  text: "The OSPi push notification script has crashed, or stopped. You should investigate this and restart it.\n\nssh to your OSPi and check /var/log/messages for errors with the script."
